-- Safe to re-run in full: every statement below is idempotent (guards existing
-- objects) so pasting this whole file into the Supabase SQL editor again after
-- a schema change never errors on "already exists".

create extension if not exists pgcrypto;

do $$ begin
  create type task_status as enum ('Backlog','In progress','Review','Done');
exception when duplicate_object then null; end $$;
do $$ begin
  create type publication_stage as enum ('Idea','Drafting','Submitted','Revision','Published');
exception when duplicate_object then null; end $$;
do $$ begin
  create type job_stage as enum ('Saved','Preparing','Applied','Interview','Offer','Closed');
exception when duplicate_object then null; end $$;

create table if not exists profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  telegram_chat_id bigint unique,
  created_at timestamptz not null default now()
);
create table if not exists projects (
  id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade,
  name text not null, description text, status text not null default 'Active', created_at timestamptz not null default now()
);
create table if not exists tasks (
  id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade,
  project_id uuid references projects(id) on delete set null, title text not null, status task_status not null default 'Backlog',
  priority text not null default 'Medium' check(priority in ('Low','Medium','High')), due_at timestamptz,
  source text not null default 'dashboard', created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists publications (
  id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade,
  title text not null, venue text, stage publication_stage not null default 'Idea', next_action text, due_at timestamptz,
  doi text, notes text, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists documents (
  id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade,
  project_id uuid references projects(id) on delete set null, title text not null, kind text not null,
  drive_file_id text, drive_url text, notes text, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists job_applications (
  id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade,
  organization text not null, role text not null, stage job_stage not null default 'Saved', url text,
  deadline timestamptz, next_action text, notes text, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists inbox_items (
  id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade,
  body text not null, source text not null default 'telegram', processed boolean not null default false, created_at timestamptz not null default now()
);

-- Telegram account linking: one-time codes generated by the dashboard, claimed by the bot
create table if not exists telegram_link_codes (
  id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade,
  code text not null unique, expires_at timestamptz not null, claimed_at timestamptz,
  created_at timestamptz not null default now()
);

-- Managed tags, shared by job applications, reminders and reads
create table if not exists tags (
  id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade,
  name text not null, color text, created_at timestamptz not null default now(),
  unique (user_id, name)
);
create table if not exists item_tags (
  tag_id uuid not null references tags(id) on delete cascade,
  entity_type text not null check (entity_type in ('job_application','reminder','read','task','publication','document')),
  entity_id uuid not null, created_at timestamptz not null default now(),
  primary key (tag_id, entity_type, entity_id)
);

create table if not exists reminders (
  id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade,
  title text not null, body text, remind_at timestamptz, done boolean not null default false,
  notified_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);

create table if not exists reads (
  id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade,
  url text not null, title text, notes text, created_at timestamptz not null default now()
);

-- Holds a single pending "add this to Reads?" confirmation per Telegram chat between
-- webhook calls. Service-role only: RLS is enabled with no policies (default-deny for
-- anon/authenticated), so only the Edge Function's service-role key can touch it.
create table if not exists telegram_pending_confirmations (
  chat_id bigint primary key, kind text not null default 'read_confirm' check (kind in ('read_confirm')),
  payload jsonb not null, created_at timestamptz not null default now(), expires_at timestamptz not null
);

alter table publications add column if not exists project_id uuid references projects(id) on delete set null;
alter table publications add column if not exists url text;
alter table job_applications add column if not exists project_id uuid references projects(id) on delete set null;
alter table tasks add column if not exists notes text;
alter table projects add column if not exists color text;
alter table reads add column if not exists read_at timestamptz;
alter table reads add column if not exists updated_at timestamptz not null default now();

-- The inline CHECK above only applies to a freshly created item_tags. Databases that
-- already ran an earlier version of this file keep the old three-type constraint, so
-- replace it explicitly to allow tagging tasks, publications and documents too.
alter table item_tags drop constraint if exists item_tags_entity_type_check;
alter table item_tags add constraint item_tags_entity_type_check
  check (entity_type in ('job_application','reminder','read','task','publication','document'));

alter table profiles enable row level security;
alter table projects enable row level security;
alter table tasks enable row level security;
alter table publications enable row level security;
alter table documents enable row level security;
alter table job_applications enable row level security;
alter table inbox_items enable row level security;
alter table telegram_link_codes enable row level security;
alter table tags enable row level security;
alter table item_tags enable row level security;
alter table reminders enable row level security;
alter table reads enable row level security;
alter table telegram_pending_confirmations enable row level security;

drop policy if exists "own profile" on profiles;
create policy "own profile" on profiles for all using (auth.uid()=id) with check (auth.uid()=id);
drop policy if exists "own projects" on projects;
create policy "own projects" on projects for all using (auth.uid()=user_id) with check (auth.uid()=user_id);
drop policy if exists "own tasks" on tasks;
create policy "own tasks" on tasks for all using (auth.uid()=user_id) with check (auth.uid()=user_id);
drop policy if exists "own publications" on publications;
create policy "own publications" on publications for all using (auth.uid()=user_id) with check (auth.uid()=user_id);
drop policy if exists "own documents" on documents;
create policy "own documents" on documents for all using (auth.uid()=user_id) with check (auth.uid()=user_id);
drop policy if exists "own jobs" on job_applications;
create policy "own jobs" on job_applications for all using (auth.uid()=user_id) with check (auth.uid()=user_id);
drop policy if exists "own inbox" on inbox_items;
create policy "own inbox" on inbox_items for all using (auth.uid()=user_id) with check (auth.uid()=user_id);
drop policy if exists "own link codes" on telegram_link_codes;
create policy "own link codes" on telegram_link_codes for all using (auth.uid()=user_id) with check (auth.uid()=user_id);
drop policy if exists "own tags" on tags;
create policy "own tags" on tags for all using (auth.uid()=user_id) with check (auth.uid()=user_id);
drop policy if exists "own reminders" on reminders;
create policy "own reminders" on reminders for all using (auth.uid()=user_id) with check (auth.uid()=user_id);
drop policy if exists "own reads" on reads;
create policy "own reads" on reads for all using (auth.uid()=user_id) with check (auth.uid()=user_id);

-- item_tags has no user_id of its own: ownership is proven by owning the tag (for
-- read/update/delete) and additionally by owning the tagged row itself (for insert/update).
drop policy if exists "own item tags" on item_tags;
create policy "own item tags" on item_tags for all
  using (exists (select 1 from tags t where t.id = item_tags.tag_id and t.user_id = auth.uid()))
  with check (
    exists (select 1 from tags t where t.id = item_tags.tag_id and t.user_id = auth.uid())
    and (
      (entity_type = 'job_application' and exists (select 1 from job_applications j where j.id = item_tags.entity_id and j.user_id = auth.uid()))
      or (entity_type = 'reminder' and exists (select 1 from reminders r where r.id = item_tags.entity_id and r.user_id = auth.uid()))
      or (entity_type = 'read' and exists (select 1 from reads rd where rd.id = item_tags.entity_id and rd.user_id = auth.uid()))
      or (entity_type = 'task' and exists (select 1 from tasks tk where tk.id = item_tags.entity_id and tk.user_id = auth.uid()))
      or (entity_type = 'publication' and exists (select 1 from publications p where p.id = item_tags.entity_id and p.user_id = auth.uid()))
      or (entity_type = 'document' and exists (select 1 from documents d where d.id = item_tags.entity_id and d.user_id = auth.uid()))
    )
  );

-- Keep updated_at current on every write path without each caller having to set it.
create or replace function set_updated_at() returns trigger
language plpgsql set search_path = public as $$
begin
  new.updated_at = now();
  return new;
end;
$$;
drop trigger if exists tasks_set_updated_at on tasks;
create trigger tasks_set_updated_at before update on tasks for each row execute function set_updated_at();
drop trigger if exists publications_set_updated_at on publications;
create trigger publications_set_updated_at before update on publications for each row execute function set_updated_at();
drop trigger if exists documents_set_updated_at on documents;
create trigger documents_set_updated_at before update on documents for each row execute function set_updated_at();
drop trigger if exists jobs_set_updated_at on job_applications;
create trigger jobs_set_updated_at before update on job_applications for each row execute function set_updated_at();
drop trigger if exists reminders_set_updated_at on reminders;
create trigger reminders_set_updated_at before update on reminders for each row execute function set_updated_at();
drop trigger if exists reads_set_updated_at on reads;
create trigger reads_set_updated_at before update on reads for each row execute function set_updated_at();

-- item_tags.entity_id can't carry a real FK (it points at one of three different
-- tables), so scrub orphaned tag links whenever a tagged row is deleted.
create or replace function fn_cleanup_item_tags() returns trigger
language plpgsql security definer set search_path = public as $$
begin
  delete from item_tags where entity_type = tg_argv[0] and entity_id = old.id;
  return old;
end;
$$;
drop trigger if exists job_applications_tag_cleanup on job_applications;
create trigger job_applications_tag_cleanup after delete on job_applications
  for each row execute function fn_cleanup_item_tags('job_application');
drop trigger if exists reminders_tag_cleanup on reminders;
create trigger reminders_tag_cleanup after delete on reminders
  for each row execute function fn_cleanup_item_tags('reminder');
drop trigger if exists reads_tag_cleanup on reads;
create trigger reads_tag_cleanup after delete on reads
  for each row execute function fn_cleanup_item_tags('read');
drop trigger if exists tasks_tag_cleanup on tasks;
create trigger tasks_tag_cleanup after delete on tasks
  for each row execute function fn_cleanup_item_tags('task');
drop trigger if exists publications_tag_cleanup on publications;
create trigger publications_tag_cleanup after delete on publications
  for each row execute function fn_cleanup_item_tags('publication');
drop trigger if exists documents_tag_cleanup on documents;
create trigger documents_tag_cleanup after delete on documents
  for each row execute function fn_cleanup_item_tags('document');

create index if not exists tasks_user_status_idx on tasks(user_id,status);
create index if not exists tasks_user_project_idx on tasks(user_id,project_id);
create index if not exists publications_user_stage_idx on publications(user_id,stage);
create index if not exists publications_user_project_idx on publications(user_id,project_id);
create index if not exists jobs_user_stage_idx on job_applications(user_id,stage);
create index if not exists jobs_user_project_idx on job_applications(user_id,project_id);
create index if not exists projects_user_idx on projects(user_id);
create index if not exists item_tags_entity_idx on item_tags(entity_type,entity_id);
create index if not exists item_tags_tag_idx on item_tags(tag_id);
create index if not exists reminders_user_remind_idx on reminders(user_id,remind_at);
create index if not exists reminders_pending_notify_idx on reminders(remind_at) where done=false and notified_at is null;
create index if not exists reads_user_created_idx on reads(user_id,created_at desc);
create index if not exists telegram_pending_confirmations_expires_idx on telegram_pending_confirmations(expires_at);
